/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayDayRouteImport } from './routes/day.$day'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayRoute = DayDayRouteImport.update({
  id: '/day/$day',
  path: '/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/welcome': typeof WelcomeRoute
  '/day/$day': typeof DayDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/welcome': typeof WelcomeRoute
  '/day/$day': typeof DayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/welcome': typeof WelcomeRoute
  '/day/$day': typeof DayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/journey' | '/welcome' | '/day/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journey' | '/welcome' | '/day/$day'
  id: '__root__' | '/' | '/journey' | '/welcome' | '/day/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JourneyRoute: typeof JourneyRoute
  WelcomeRoute: typeof WelcomeRoute
  DayDayRoute: typeof DayDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$day': {
      id: '/day/$day'
      path: '/day/$day'
      fullPath: '/day/$day'
      preLoaderRoute: typeof DayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JourneyRoute: JourneyRoute,
  WelcomeRoute: WelcomeRoute,
  DayDayRoute: DayDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
